### ISSUE TITLE
Release 0.45 has wrong installed

### ISSUE THREAD

**Issue by NoFoolLikeOne** [inorton/EDMCOverlay#10]
This appears to be the HITS installer

**Comment by inorton** [comment]
Yes, that's right, hits contains the overlay server

**Comment by NoFoolLikeOne** [comment]
Does that mean you cant install the overlay without also installing HITS?

**Comment by inorton** [comment]
Is that what you want to do?

**Comment by inorton** [comment]
0.4.10 of HITS installs the overlay now (I won't be doing two different releases) in the HITS preferences dialog in EDMC you can set it to stop displaying the traffic report by settings "traffic reports" to "off"
