### ISSUE TITLE
Windows 10 complains about the MSI + publisher field says Unknown

### ISSUE THREAD

**Issue by lekeno** [inorton/EDMCOverlay#15]
Not sure you can easily do anything[1] about the first issue but probably the "Unknown Publisher" could be an easy fix and a simple way to increase trust in the installer?

[1]: there might a way to submit your binary/msi for false positive review. I did this for my copy of EDMCOverlay.exe and it seems to have helped.

**Comment by inorton** [comment]
Hmm, maybe I uploaded an unsigned one?

**Comment by inorton** [comment]
Hmm...  I just re-downloaded it.  I get the "Windows Protected your PC" dialog and when I click "more info" It correctly shows EDMCOverlay as the publisher.

What happens if you download the ca cert and install that first?

**Comment by inorton** [comment]
Ok, righty, the "Smartscreen" stuff has nothing to do with the signature.  You can either save the MSI and "unblock" it in the file properties or click "more info" and "run anyway".

Once I do that I have the correct publisher set.

**Comment by lekeno** [comment]
OK, no big deal :)
