### ISSUE TITLE
EDMC Overlay consuming large amounts of drive space

### ISSUE THREAD

**Issue by Meridianstream** [inorton/EDMCOverlay#16]
![screenshot 2018-05-24 13 22 15](https://user-images.githubusercontent.com/19539849/40485892-9f43881c-5f57-11e8-9369-215e1bda0be6.png)

Hi the file edmcoverlay.log is huge …. I have been using EDMC Overlay as an included part of EDR and have noticed this issue. Hopefully the screenshot is uploaded ok.

thanks

**Comment by inorton** [comment]
Wow that is an impressive amount of space!  I will implement log rolling :)

**Comment by inorton** [comment]
Update, had another report of this. But I had actually already implemented measures to ensure the log did not grow - see https://github.com/inorton/EDMCOverlay/blob/master/EDMCOverlay/EDMCOverlay/Logger.cs#L16

**Comment by austeregrim** [comment]
Still exists, had the problem with mine. I think its a problem with overlay trying to log/cache the images the screenshot plugin shows on the edmc screen.

**Comment by inorton** [comment]
I've found the problem.  If EDMC is restarted while the overlay is running, the overlay writes MANY duplicate messages about the client disconnecting until the overlay stops.

If Elite is stopped the overlay will exit and the log will stop growing

If Elite is started up again fresh the log will be truncated.

*Workaround* Exit Elite or terminate the EDMCOverlay process and delete the log if the file remains.

**Comment by inorton** [comment]
Fixed in 1.0.1
