### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by FizzerUK** [inorton/EDMCOverlay#17]
Can not install program.
System can not open device or file specified
Error code: 2755

[Cut_Error_log.txt](https://github.com/inorton/EDMCOverlay/files/2109017/Cut_Error_log.txt)

Windows 10 Release Id: 1803 (64-bit)

**Comment by inorton** [comment]
Hi @FizzerUK this could be because your system restore is disabled:

```
MSI (s) (68:F8) [14:25:31:470]: Calling SRSetRestorePoint API. dwRestorePtType: 0, dwEventType: 102, llSequenceNumber: 0, szDescription: "Installed EDMC Overlay".
MSI (s) (68:F8) [14:25:31:470]: The System Restore service is disabled. Returned status: 1058. GetLastError() returned: 1058
```
