### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by nolt** [inorton/EDMCOverlay#19]
Hi,

I've installed this plugin yesterday and when I've started ED I got message /EDMC Overlay/ and no futher messages. I'm explorer, at now I'm somewhere in void in totaly unexplored systems. While I jump I don't see any messages from EDMCOverlay.

Maybe I need another plugin?
More detailed "HowToUse" readme would be nice.

**Comment by inorton** [comment]
Hi there!

The plugin itself is supposed to be used by other EDMC plugins to be able to display data on screen in-game.

The HITS plugin will render on the overlay information about the number of other ships that have visited the current system.

https://github.com/inorton/EDMCHits/releases

If you have an idea for an explorer plugin that could render on the overlay let me know,   I have a "speedometer" plugin that I might update to draw on the overlay too.

https://github.com/inorton/EDMCJumpSpeed

**Comment by nolt** [comment]
Speedometr is a nice.

For explorer plugin here are mine ideas:
- report amount of cash for scanned body - important
- report of fuel tank (i.e 75%, 50%,  25% and 5% with info refuel is necssary)  - very important
- report if destinated star is scoopable or not - very important
- report what type is destinated star - not important but would be nice
