### ISSUE TITLE
Repeated attempts using EDMCOverlay with EDR

### ISSUE THREAD

**Issue by WarxThane** [inorton/EDMCOverlay#20]
I've tried EDMCO with both HITS and EDR and nothing seems to get EDMCO working at all.

I've done fresh installs of EDMCO with HITS and EDR separately, and can't find any troubleshooting tips anywhere.

**Comment by WarxThane** [comment]
I can see EDMCO pop in and out while holding Alt+Tab but never appears over elite, and its in borderless

**Comment by inorton** [comment]
Hi @WarxThane can I ask what sort of graphics card and what version of windows you have?

I have an NVidia 970 GTX, Before that It worked on my 740 GTX and GT9600 quite well.

**Comment by WarxThane** [comment]
@inorton I have a Nvidia 1070 GTX, with Windows 10 PRO

**Comment by inorton** [comment]
Hi @WarxThane 

What screen resolution are you running at?   Do you have an edmcoverlay.log file you could send me?

**Comment by inorton** [comment]
Hmm. Thank you all for the details.

I'm totally stumped but it seems 10xx cards is the common theme.

**Comment by HavocRS** [comment]
Same problem here, EDMC is not shown in the game

**Comment by inorton** [comment]
The directx calls I make from c# are the subject of much debate, there are things that apparently just should work fine on all cards but sometimes quirks you need to do before drawing on the screen.

Occasionally on my system it will draw nothing, or only draw in a small corner of the screen.

**Comment by incryptx** [comment]
I think I have the same issue, on a 1070Ti with the latest drivers. I am using borderless as well.

When starting the game, I have /edmc/overlay/ displayed when seeing the spinning ship, but nothing after this. My resolution is 3840x2160. I also use EDR and HITS, as well as ExTool.

**Comment by youloveben** [comment]
Just chiming in to say "me too". 

One monitor, GTX1070 w/ updated drivers, borderless, 1920x1080, and the kicker for me is that _it worked fine last year_... any suggestions?

[edmcoverlay.log](https://github.com/inorton/EDMCOverlay/files/3188697/edmcoverlay.log)

**Comment by youloveben** [comment]
[How_to_-_ED_Recon.pdf](https://github.com/inorton/EDMCOverlay/files/3188791/How_to_-_ED_Recon.pdf)

This helped me get it to work again; Section D specifically. Props to LeKeno!

**Comment by inorton** [comment]
Oh I get it now!  EDR doesn't render onto the overlay by default!

**Comment by inorton** [comment]
Possibly fixed in 1.0.6
