### ISSUE TITLE
VR Support

### ISSUE THREAD

**Issue by ACyprus** [inorton/EDMCOverlay#21]
Hello Ian

Thank you for your efforts and innovation.

I understand you currently support the following modes only:

- Windowed
- Bordless Fullscreen

I'm hoping to integrate some overlays into my game-play as a Fuel Rat in VR, and was wondering if you have any plans to support this mode in future? 

This is not an official request from the Fuel Rats, but should a solution be viable, I intend to share the results with the Fuel Rat Mischief and hope to benefit the wider VR user base within it.

The Fuel Rat dispatch and rescue process is managed outside the game via 3rd party client and/or web apps. During a rescue, a Rat must alt+tab between game and other windows multiple times to review instructions and/or provide updates on progress.

In VR, this becomes even more tiresome, as various existing solutions for "pinning" desktop windows into the VR space so we can actually see them without removing the VR headset are sub-optimal. 

Use of EDMC Overlay to confirm/alert the VR Rat to various stages of a rescue would be invaluable and greatly speed the process.

I'm using an Oculus Rift and would be happy to help test the solution assuming you do not own a headset yourself.

Right now, the overlay messages sent by my test EDMC plugin are painted onto the "Elite - Dangerous(CLIENT)" mirror window correctly but are not visible via the VR headset.

Many thanks.

**Comment by inorton** [comment]
I have been having some ideas that might solve the VR problem, is it possible to display a small browser window in your headset?

**Comment by lekeno** [comment]
@inorton @ACyprus Hi, I got EDMCOverlay to work in VR (and in multi-monitor setups too). See the pull request above.

**Comment by nullx8** [comment]
is there a known trick to get it to work in VR using native SteamVr or OculusVR ? 
overlays work perfectly on the monitor but they do not show when the game is transferred trough steamvr

**Comment by lekeno** [comment]
Hopefully this helps: https://www.youtube.com/watch?v=BPJFV4ycP3k

With EDR, you first need to change the overlay to be standalone in the settings (accessible via ED Market Connector).

You also need to add the standalone overlay into the VR scene via SteamVR (i.e. you need to be in VR mode to do so).

**Comment by nullx8** [comment]
thanks alot, for some reason i can only capture the main program and once the game starts everything moves into the background, the only way to get it to work is to use desktop/screen mode, but then its just like running of a flatscreen.

**Comment by inorton** [comment]
I have no access to VR so unless someone else wants to I cant look into this
