### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by tonkepen100** [inorton/EDMCOverlay#3]
Hello:

I get in touch with you since after putting a complement, in this case EDMC HITS, I see and verify, that the memory that spends its mod, is super high, there are almost moments that surpasses the game itself.

We consider that we should review this point in order to refine it.

Attachment I let you capture one of the moments of the game ...

![captura](https://user-images.githubusercontent.com/4571086/28385277-cdb9c964-6cc7-11e7-9670-ca9033e80747.PNG)

Thank you for your attention.

**Comment by inorton** [comment]
Hi there, thank-you.  Yes, I've been meaning to look at the resource usage and might have some time. I do have a quite simple fix in mind for it.

The column you have highlighted though is CPU use.  As EDMCOverlay draws on top of the directx screen it can eat rather alot of CPU.  But as I say, my pending idea should help.

**Comment by tonkepen100** [comment]
Yes, that's right, but what can not be is that only with those processes, it is consuming at peaks more than the rest of the remaining applications. And Think I just put those apps to watch consumption. As you will understand, when playing there are many more, say browsers, Discovery, and many others that I do not define.

On the other hand, I also tell you, that exploring at this time, about 22000. its popup, it leaves when it gives the real gain, other than that I understand, it is not an addon for it. I perfectly understand.

But if I understand that your idea is brilliant, and you have a sensational future.

If you need any help to continue with your project, please do not hesitate to tell me, I'll be happy to help you, as you ask.

admin@piro.biz
Ts.piro.biz

Thank you for your attention.

**Comment by inorton** [comment]
Try the latest version of HITS, I just uploaded a new package.

**Comment by tonkepen100** [comment]
Sorry, I was out and I did not answer your answer.

Thanks for that, now I'm going down again and I'm pogo your changes to see if it really is softer.

I tell you.

**Comment by inorton** [comment]
I'm going to consider this fixed now, made some efficiency fixes recently and had no complaints so far
