### ISSUE TITLE
Typo in send_raw

### ISSUE THREAD

**Issue by fiinnnn** [inorton/EDMCOverlay#31]
Hi,
I had some issues getting the overlay to work when I noticed a typo here:
https://github.com/inorton/EDMCOverlay/blob/57bf27d3edc3f63ed69d02c38648606176019433/edmcoverlay.py#L139
After changing it to `connection` everything works as expected.

**Comment by x2611** [comment]
Hi,

Made the change yet EDMCOverlay.exe is not running in Task Manager.

EDMarketConnector_win_4.0.2.0.msi
EDMCOverlay-1.0.4.msi
EDR.v1.0.9.zip

**Comment by inorton** [comment]
Whoops!:D

**Comment by inorton** [comment]
Fixed in https://github.com/inorton/EDMCOverlay/releases/tag/1.0.5
