### ISSUE TITLE
Suggestion to Add a Github Topic

### ISSUE THREAD

**Issue by dylan-k** [inorton/EDMCOverlay#34]
Github has a tags feature that I've found to be quite useful for finding [repos related to Elite Dangerous](https://github.com/topics/elite-dangerous). I noticed that this one might benefit from adding the `elite-dangerous` tag. Github calls them topics and says: To associate your repository with the elite-dangerous topic, visit your repo's landing page and select "manage topics." I'm very glad I found this fun app, and hope this would help others to do so as well.

**Comment by inorton** [comment]
Thanks I did add the tag but forgot to say thank-you!
