### ISSUE TITLE
edmcoverlay.py doesn't work as a stand-alone script

### ISSUE THREAD

**Issue by MarvSR** [inorton/EDMCOverlay#35]
Hi,
it seems that ED overlay  isnt working for me.

If i run the edmoverlay.py, i have two problems:
Import "monitor" could not be resolved
Import "load" could not be resolved

**Comment by inorton** [comment]
Hi @MarvSR 

The edmcoverlay.py file is not meant to be run stand-alone, it is supposed to imported by an EDMC plugin.
