### ISSUE TITLE
Error pop-up on start up

### ISSUE THREAD

**Issue by TonyFlury** [inorton/EDMCOverlay#46]
I am using Windows 11,  EDMC Release 5.11.3 (the latest as of 21 August 2024. and I have installed EDMCOverlay-1.0.6 for Windows.

On EDMC startup I get this pop-up
![image](https://github.com/user-attachments/assets/f395cb80-06c8-4f87-840f-305bb6c673b7)

I have check the plugin folder and i see this structure

![image](https://github.com/user-attachments/assets/aec45224-6931-4a85-a9ad-209ba93925bc)

The load.py appears to be in the right place.

The machine has Python 3.12.3 installed as default.

Other plugins (EDMC-Cannon) work fine.

**Comment by Ignalion** [comment]
Put EDMCOverlay.exe into plugin folder.
Yes, it says that literally nowhere and there is no proper error handling but basically the plugin loading fails because it can't find EDMCOverlay.exe

**Comment by Ignalion** [comment]
No, disregard that. Just delete plugin folder overall, download .msi file and run it. It does something different from just putting .exe and plugin code into the place, after putting EDMCOverlay.exe it stopped failing but still didn't work properly

**Comment by inorton** [comment]
Hi folks, I've not had a chance to try the app on windows 11. Plus the version of python you have shouldn't really make any difference as the overlay system will be using the python bundled with EDMC.

I've not made any attempt to maintain this recently.

**Comment by aussig** [comment]
It's working perfectly for me on Win 11.  The file structure in the OPs screenshot looks wrong to me - did you install this from source instead of the installer? On a clean (working) install of the plugin, I get this structure:

![image](https://github.com/user-attachments/assets/b380a40d-ea34-49d7-aeff-14fca7d44e0a)

**Comment by inorton** [comment]
Can't reproduce
