### ISSUE TITLE
Keep getting client disconnect on debug log

### ISSUE THREAD

**Issue by LuizRGB** [inorton/EDMCOverlay#47]
My overlay debug log is full of client disconnect while the game is still running. I'll attach the log.
[edmcoverlay.log](https://github.com/user-attachments/files/16860284/edmcoverlay.log)
I'm running Odissey, from an Epic account.

**Comment by LuizRGB** [comment]
I got this second log, with some messages exchanged between the server and the client. This could indicate a port or firewall issue?
[edmcoverlay.log](https://github.com/user-attachments/files/16860397/edmcoverlay.log)
During all the log duration the client was running.

**Comment by inorton** [comment]
The connect/disconnect messages don't signify any kind of error, its just how the system works, some threads or other plugins (like EDR) will directly connect to the server and you get these messages

**Comment by LuizRGB** [comment]
I managed for it to work, but it's not working in fullscreen. Is this a limitation?

**Comment by aussig** [comment]
Yes, windowed or full screen borderless only, as clearly stated in the Compatibility section of the README: https://github.com/inorton/EDMCOverlay?tab=readme-ov-file#compatibility
