### ISSUE TITLE
EDMCOverlay window isn't closed with EDMC

### ISSUE THREAD

**Issue by Rohaq** [inorton/EDMCOverlay#6]
Originally an issue over at EDMC: https://github.com/Marginal/EDMarketConnector/issues/257

The EDMCOverlay window isn't closed when you exit the game or EDMC, requiring it to be closed manually either via Task Manager/Process Explorer, or from the alt-tab selector (Windows 10).

@Marginal suggests:
@inorton Could you use the plugin_stop() callback (added in EDMC 2.40) to tidy up the EDMCOverlay window?

**Comment by inorton** [comment]
Fixed in the 0.4.10 HITS release https://github.com/inorton/EDMCHits/
