### ISSUE TITLE
Shapes don't seem to be scaled up from the virtual screen to the actual screen dimensions

### ISSUE THREAD

**Issue by lekeno** [inorton/EDMCOverlay#7]
Hi,

It seems that the shapes (rect for sure) are not scaled up from the virtual screen to the actual screen.
From a quick look, it seems that the Scale function is partially called but not used for the shapes.

**Comment by inorton** [comment]
Fixed on master, will close this when I build a new MSI

**Comment by inorton** [comment]
Fixed in the 0.4.10 HITS release
